# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ main ]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/


      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           minor-wording:  '1,new'
      - run: git config --global user.email "sun@wuyuan.dev"
      - run: git config --global user.name "SunWuyuan"
      - run: npm i
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
